---
deployment:
  tasks:
    - export DEPLOYPATH=/home/u8734491/public_html/
    - /bin/cp -R root $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp -R img $DEPLOYPATH
    - /bin/cp -R pbd $DEPLOYPATH
    - /bin/cp -R dashboard $DEPLOYPATH
